-- 0042_playlist_discovery_group.sql
--
-- Rename playlist discovery version terminology to playlist discovery groups
-- and normalize the first two production playlist cohorts.

begin;

create table if not exists wg_playlist_discovery_groups (
    playlist_discovery_group text primary key,
    label                    text not null,
    legacy_discovery_version text,
    notes                    text not null default '',
    created_at               timestamptz not null default now()
);

insert into wg_playlist_discovery_groups (
    playlist_discovery_group,
    label,
    legacy_discovery_version,
    notes
)
values
    (
        'group_1',
        'YouTube track match from Spotify/YTMusic crawl',
        'youtube_track_match_ytmusic_20260525',
        'Initial production playlist rows generated by the YTMusic track-matching pipeline.'
    ),
    (
        'group_2',
        'Reviewed YouTube Music direct playlist rows',
        'ytmusic_reviewed_direct_20260526',
        'Accepted YouTube Music playlist rows imported directly after review.'
    ),
    (
        'group_3',
        'Displayable live genres missing from permanent storage',
        null,
        'Displayable/traversable live genre gap set queued for future playlist discovery.'
    )
on conflict (playlist_discovery_group) do update set
    label = excluded.label,
    legacy_discovery_version = excluded.legacy_discovery_version,
    notes = excluded.notes;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'wg_genre_youtube_playlist_tracks'
          and column_name = 'discovery_version'
    ) and not exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'wg_genre_youtube_playlist_tracks'
          and column_name = 'playlist_discovery_group'
    ) then
        alter table wg_genre_youtube_playlist_tracks
            rename column discovery_version to playlist_discovery_group;
    end if;
end $$;

alter table wg_genre_youtube_playlist_tracks
    add column if not exists playlist_discovery_group text not null default 'manual';

alter table wg_genre_youtube_playlist_tracks
    alter column playlist_discovery_group set default 'manual';

update wg_genre_youtube_playlist_tracks
set playlist_discovery_group = case playlist_discovery_group
    when 'youtube_track_match_ytmusic_20260525' then 'group_1'
    when 'ytmusic_reviewed_direct_20260526' then 'group_2'
    else playlist_discovery_group
end;

drop index if exists wg_genre_youtube_playlist_tracks_discovery_version;

create index if not exists wg_genre_youtube_playlist_tracks_playlist_discovery_group
    on wg_genre_youtube_playlist_tracks(playlist_discovery_group, genre_id);

commit;
