-- 0044_genre_semantic_layout_radial_compaction.sql
--
-- Optional display coordinates generated by radial constrained rectangle
-- compaction. The semantic layout coordinates in x/y remain the source
-- anchors; these columns store a denser inward-packed view.

begin;

alter table if exists wg_genre_semantic_layouts
    add column if not exists radial_x double precision,
    add column if not exists radial_y double precision,
    add column if not exists radial_compaction_version text,
    add column if not exists radial_compaction_quality jsonb not null default '{}'::jsonb,
    add column if not exists radial_compacted_at timestamptz;

create index if not exists wg_genre_semantic_layouts_radial_view_idx
    on wg_genre_semantic_layouts(layout_key, radial_x, radial_y)
    where radial_x is not null and radial_y is not null;

commit;
